name: JavaScript CI

on:
  push:
    branches:
      - shivademo-learn-CI-CD-1

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Files
        run: |
          echo "Project checked successfully"
